export const COLLABORATOR_MENU_LIST = [
  {
    modalTitle: 'Registro de Cargos Colaboradores',
    menuName: 'Cargos Colaboradores',
    entity: 'collaborators-office-changes',
    icon: 'supervisor_account',
  },
  {
    modalTitle: 'Registro de Sexo',
    menuName: 'Sexo',
    entity: 'collaborators-sex-changes',
    icon: 'supervisor_account',
  },
  {
    modalTitle: 'Registro de Estado Civil',
    menuName: 'Estado Cívil',
    entity: 'collaborators-charges',
    icon: 'supervisor_account',
  },
  {
    modalTitle: 'Registro de Tipo Relacionamento',
    menuName: 'Tipo Relacionamento',
    entity: 'collaborators-charges',
    icon: 'supervisor_account',
  },
  {
    modalTitle: 'Registro de Grau de Instrução',
    menuName: 'Grau de Instrução',
    entity: 'collaborators-charges',
    icon: 'supervisor_account',
  },
  {
    modalTitle: 'Registro de Situação Instrução',
    menuName: 'Situação Instrução',
    entity: 'collaborators-charges',
    icon: 'supervisor_account',
  },
  {
    modalTitle: 'Registro de Idiomas',
    menuName: 'Idiomas',
    entity: 'collaborators-charges',
    icon: 'supervisor_account',
  },
  {
    modalTitle: 'Registro de Tecnologias',
    menuName: 'Tecnologias',
    entity: 'collaborators-charges',
    icon: 'supervisor_account',
  },
  {
    modalTitle: 'Registro de Senioridade',
    menuName: 'Senioridade',
    entity: 'collaborators-charges',
    icon: 'supervisor_account',
  },
  {
    modalTitle: 'Registro de Motivo Mudança Salário',
    menuName: 'Motivo Mudança Salário',
    entity: 'collaborators-charges',
    icon: 'supervisor_account',
  },
  {
    modalTitle: 'Registro de Cargos Colaboradores',
    menuName: 'Cargos Colaboradores',
    entity: 'collaborators-charges',
    icon: 'supervisor_account',
  },
  {
    modalTitle: 'Registro de Cargos Colaboradores',
    menuName: 'Cargos Colaboradores',
    entity: 'collaborators-charges',
    icon: 'supervisor_account',
  },
  {
    modalTitle: 'Registro de Cargos Colaboradores',
    menuName: 'Cargos Colaboradores',
    entity: 'collaborators-charges',
    icon: 'supervisor_account',
  },
  {
    modalTitle: 'Registro de Cargos Colaboradores',
    menuName: 'Cargos Colaboradores',
    entity: 'collaborators-charges',
    icon: 'supervisor_account',
  },
  {
    modalTitle: 'Registro de Cargos Colaboradores',
    menuName: 'Cargos Colaboradores',
    entity: 'collaborators-charges',
    icon: 'supervisor_account',
  },
  {
    modalTitle: 'Registro de Cargos Colaboradores',
    menuName: 'Cargos Colaboradores',
    entity: 'collaborators-charges',
    icon: 'supervisor_account',
  },
];
